controller_frequency: 20.0
TrajectoryPlannerROS:
  max_vel_x: 0.80
  min_vel_x: 0.01
  max_rotational_vel: 1.2
  min_in_place_rotational_vel: 0.8
  acc_lim_th: 0.4
  acc_lim_x: 0.3
  acc_lim_y: 0.3

  holonomic_robot: false
  meter_scoring: true
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15
  goal_distance_bias: 0.8
  path_distance_bias: 3.0
  sim_time: 1.5
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.1

  vx_samples: 6
  vtheta_samples: 20
  dwa: false

