/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-electric-common-msgs-1.6.0/debian/ros-electric-common-msgs/opt/ros/electric/stacks/common_msgs/diagnostic_msgs/msg/KeyValue.msg */
#ifndef DIAGNOSTIC_MSGS_MESSAGE_KEYVALUE_H
#define DIAGNOSTIC_MSGS_MESSAGE_KEYVALUE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace diagnostic_msgs
{
template <class ContainerAllocator>
struct KeyValue_ {
  typedef KeyValue_<ContainerAllocator> Type;

  KeyValue_()
  : key()
  , value()
  {
  }

  KeyValue_(const ContainerAllocator& _alloc)
  : key(_alloc)
  , value(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _key_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  key;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _value_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  value;


private:
  static const char* __s_getDataType_() { return "diagnostic_msgs/KeyValue"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "cf57fdc6617a881a88c16e768132149c"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string key # what to label this value when viewing\n\
string value # a value to track over time\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, key);
    ros::serialization::serialize(stream, value);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, key);
    ros::serialization::deserialize(stream, value);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(key);
    size += ros::serialization::serializationLength(value);
    return size;
  }

  typedef boost::shared_ptr< ::diagnostic_msgs::KeyValue_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diagnostic_msgs::KeyValue_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct KeyValue
typedef  ::diagnostic_msgs::KeyValue_<std::allocator<void> > KeyValue;

typedef boost::shared_ptr< ::diagnostic_msgs::KeyValue> KeyValuePtr;
typedef boost::shared_ptr< ::diagnostic_msgs::KeyValue const> KeyValueConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::diagnostic_msgs::KeyValue_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::diagnostic_msgs::KeyValue_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace diagnostic_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::diagnostic_msgs::KeyValue_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::diagnostic_msgs::KeyValue_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::diagnostic_msgs::KeyValue_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cf57fdc6617a881a88c16e768132149c";
  }

  static const char* value(const  ::diagnostic_msgs::KeyValue_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcf57fdc6617a881aULL;
  static const uint64_t static_value2 = 0x88c16e768132149cULL;
};

template<class ContainerAllocator>
struct DataType< ::diagnostic_msgs::KeyValue_<ContainerAllocator> > {
  static const char* value() 
  {
    return "diagnostic_msgs/KeyValue";
  }

  static const char* value(const  ::diagnostic_msgs::KeyValue_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::diagnostic_msgs::KeyValue_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string key # what to label this value when viewing\n\
string value # a value to track over time\n\
\n\
";
  }

  static const char* value(const  ::diagnostic_msgs::KeyValue_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::diagnostic_msgs::KeyValue_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.key);
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct KeyValue_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diagnostic_msgs::KeyValue_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::diagnostic_msgs::KeyValue_<ContainerAllocator> & v) 
  {
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.key);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DIAGNOSTIC_MSGS_MESSAGE_KEYVALUE_H

